# Generated by Django 5.2.8 on 2026-01-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCurrency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('currency_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dim_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_date', models.DateField()),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quarter_end', models.DateField()),
            ],
            options={
                'db_table': 'dim_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimFund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('legal_form', models.CharField(blank=True, max_length=100, null=True)),
                ('management_company', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_strategy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_fund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPhase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dim_phase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimScenarioList',
            fields=[
                ('scenario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
            ],
            options={
                'db_table': 'dim_scenario_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTimeframe',
            fields=[
                ('timeframe_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_label', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dim_timeframe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimScenarioSynthesis',
            fields=[
                ('synthesis_id', models.AutoField(primary_key=True, serialize=False)),
                ('synthesis_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('fund', models.ForeignKey(db_column='fund_id', on_delete=django.db.models.deletion.CASCADE, to='rest_api.dimfund')),
            ],
            options={
                'db_table': 'dim_scenario_synthesis',
            },
        ),
        migrations.CreateModel(
            name='DimShareClass',
            fields=[
                ('share_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('share_class_name', models.TextField()),
                ('isin_code', models.TextField()),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('issuance_method', models.TextField()),
                ('distribution_method', models.TextField(choices=[('DIVIDEND', 'Dividend'), ('REDEMPTION_OF_SHARES', 'Redemption of Shares')])),
                ('ppm_description', models.TextField()),
                ('document_name', models.TextField(blank=True, null=True)),
                ('document_mime_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('fund', models.ForeignKey(db_column='fund_id', on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='rest_api.dimfund')),
            ],
            options={
                'db_table': 'dim_share_class',
            },
        ),
        migrations.CreateModel(
            name='MapScenarioSynthesis',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario', models.ForeignKey(db_column='scenario_id', on_delete=django.db.models.deletion.CASCADE, to='rest_api.dimscenariolist')),
                ('synthesis', models.ForeignKey(db_column='synthesis_id', on_delete=django.db.models.deletion.CASCADE, related_name='scenario_mappings', to='rest_api.dimscenariosynthesis')),
            ],
            options={
                'db_table': 'map_scenario_synthesis',
            },
        ),
        migrations.AddConstraint(
            model_name='dimscenariosynthesis',
            constraint=models.UniqueConstraint(fields=('fund', 'synthesis_name'), name='unique_synthesis_per_fund'),
        ),
        migrations.AddConstraint(
            model_name='dimshareclass',
            constraint=models.UniqueConstraint(fields=('fund', 'share_class_name'), name='uq_share_class_fund_name'),
        ),
    ]
