# Generated by Django 5.2.8 on 2026-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimshareclass',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='share_class_docs/'),
        ),
    ]
