# Generated by Django 5.2.10 on 2026-01-27 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_dimshareclass_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('iso2_code', models.CharField(max_length=2, unique=True)),
                ('iso3_code', models.CharField(max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundPhase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fund_phase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManFeePhase',
            fields=[
                ('phase_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=50)),
                ('basis_description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'man_fee_phase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('share_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_class_name', models.CharField(max_length=100)),
                ('isin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('issuance_method', models.CharField(choices=[('Pro Rata Called Amount', 'Pro Rata Called Amount'), ('Upfront', 'Upfront')], max_length=50)),
                ('distribution_method', models.CharField(choices=[('Redemption of Shares', 'Redemption of Shares'), ('Dividend', 'Dividend')], max_length=50)),
                ('ppm_description', models.TextField(blank=True, null=True)),
                ('document_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'share_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('timeframe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('quarter', models.DecimalField(decimal_places=0, editable=False, max_digits=2)),
                ('year', models.DecimalField(decimal_places=0, editable=False, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'timeframe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('phase_name', models.CharField(max_length=100)),
                ('legal_form', models.CharField(blank=True, max_length=100, null=True)),
                ('management_company', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_strategy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, to='rest_api.currency')),
            ],
            options={
                'db_table': 'fund',
            },
        ),
        migrations.CreateModel(
            name='FundManFeeRules',
            fields=[
                ('fee_rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_until', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('fund', models.ForeignKey(db_column='fund_id', on_delete=django.db.models.deletion.CASCADE, related_name='man_fees', to='rest_api.fund')),
                ('phase', models.ForeignKey(db_column='phase_id', on_delete=django.db.models.deletion.PROTECT, related_name='man_fees', to='rest_api.manfeephase')),
                ('share_class', models.ForeignKey(blank=True, db_column='share_class_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='man_fees', to='rest_api.shareclass')),
            ],
            options={
                'db_table': 'fund_man_fee_rules',
            },
        ),
        migrations.CreateModel(
            name='FundWaterfallEnvelopes',
            fields=[
                ('waterfall_envelope_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('envelope_number', models.PositiveIntegerField()),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fund_waterfall_envelopes',
            },
        ),
        migrations.CreateModel(
            name='FundWaterfallRules',
            fields=[
                ('waterfall_rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_pro_rata', models.BooleanField(default=False)),
                ('fixed_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('envelope', models.ForeignKey(db_column='waterfall_envelope_id', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rest_api.fundwaterfallenvelopes')),
                ('share_class', models.ForeignKey(db_column='share_class_id', on_delete=django.db.models.deletion.CASCADE, to='rest_api.shareclass')),
            ],
            options={
                'db_table': 'fund_waterfall_rules',
            },
        ),
        migrations.CreateModel(
            name='FundWaterfallSteps',
            fields=[
                ('fund_waterfall_step_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255)),
                ('step_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('fund', models.ForeignKey(db_column='fund_id', on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_steps', to='rest_api.fund')),
            ],
            options={
                'db_table': 'fund_waterfall_steps',
            },
        ),
        migrations.CreateModel(
            name='ScenarioSynthesis',
            fields=[
                ('synthesis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('synthesis_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(db_column='fund_id', on_delete=django.db.models.deletion.CASCADE, related_name='syntheses', to='rest_api.fund')),
            ],
            options={
                'db_table': 'scenario_synthesis',
            },
        ),
        migrations.CreateModel(
            name='WaterfallStep',
            fields=[
                ('waterfall_step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'waterfall_step',
                'ordering': ['step_number'],
            },
        ),
        migrations.RemoveField(
            model_name='dimscenariosynthesis',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='dimshareclass',
            name='fund',
        ),
        migrations.DeleteModel(
            name='DimCurrency',
        ),
        migrations.DeleteModel(
            name='DimDate',
        ),
        migrations.DeleteModel(
            name='DimPhase',
        ),
        migrations.DeleteModel(
            name='DimTimeframe',
        ),
        migrations.AlterModelOptions(
            name='scenariolist',
            options={},
        ),
        migrations.AlterField(
            model_name='mapscenariosynthesis',
            name='record_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fundwaterfallenvelopes',
            name='fund_waterfall_steps',
            field=models.ForeignKey(db_column='fund_waterfall_step_id', on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='rest_api.fundwaterfallsteps'),
        ),
        migrations.AlterField(
            model_name='mapscenariosynthesis',
            name='synthesis',
            field=models.ForeignKey(db_column='synthesis_id', on_delete=django.db.models.deletion.CASCADE, related_name='scenario_mappings', to='rest_api.scenariosynthesis'),
        ),
        migrations.AlterUniqueTogether(
            name='mapscenariosynthesis',
            unique_together={('synthesis', 'scenario')},
        ),
        migrations.AddField(
            model_name='fundwaterfallsteps',
            name='step_definition',
            field=models.ForeignKey(db_column='waterfall_step_id', on_delete=django.db.models.deletion.PROTECT, related_name='fund_instances', to='rest_api.waterfallstep'),
        ),
        migrations.DeleteModel(
            name='DimShareClass',
        ),
        migrations.DeleteModel(
            name='DimFund',
        ),
        migrations.AddConstraint(
            model_name='fundmanfeerules',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phase_id', 1), ('share_class__isnull', False)), models.Q(('phase_id', 2), ('share_class__isnull', True)), _connector='OR'), name='chk_phase_share_class'),
        ),
        migrations.AddConstraint(
            model_name='fundmanfeerules',
            constraint=models.CheckConstraint(condition=models.Q(('date_until__isnull', True), ('date_until__gt', models.F('date_from')), _connector='OR'), name='chk_date_range'),
        ),
        migrations.AddConstraint(
            model_name='fundwaterfallrules',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_percentage__gte', 0), ('fixed_percentage__lte', 100)), ('fixed_percentage__isnull', True), _connector='OR'), name='chk_fixed_percentage_range'),
        ),
        migrations.AlterUniqueTogether(
            name='fundwaterfallrules',
            unique_together={('envelope', 'share_class')},
        ),
        migrations.AddConstraint(
            model_name='fundwaterfallenvelopes',
            constraint=models.UniqueConstraint(fields=('fund_waterfall_steps', 'envelope_number'), name='uq_waterfall_envelope_step_number'),
        ),
        migrations.AddConstraint(
            model_name='scenariosynthesis',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('fund', 'synthesis_name'), name='uq_active_synthesis_per_fund'),
        ),
        migrations.DeleteModel(
            name='DimScenarioSynthesis',
        ),
        migrations.AddConstraint(
            model_name='fundwaterfallsteps',
            constraint=models.UniqueConstraint(fields=('fund', 'step_definition'), name='uq_fund_waterfall_step_fund_stepdef'),
        ),
    ]
