# Generated by Django 5.2.10 on 2026-01-28 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_country_currency_fundphase_manfeephase_shareclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundWaterfallEnvelopeRules',
            fields=[
                ('envelope_rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_pro_rata', models.BooleanField(default=False)),
                ('fixed_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fund_waterfall_envelope_rules',
            },
        ),
        migrations.CreateModel(
            name='FundWaterfallStepRules',
            fields=[
                ('step_rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_pro_rata', models.BooleanField(default=False)),
                ('fixed_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fund_waterfall_step_rules',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fundwaterfallrules',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fundwaterfallrules',
            name='envelope',
        ),
        migrations.RemoveField(
            model_name='fundwaterfallrules',
            name='share_class',
        ),
        migrations.AlterModelOptions(
            name='shareclass',
            options={},
        ),
        migrations.AddField(
            model_name='scenariolist',
            name='fund',
            field=models.ForeignKey(db_column='fund_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='rest_api.fund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenariolist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenariolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scenariolist',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scenariolist',
            name='scenario_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='scenariolist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('fund', 'scenario_name'), name='uq_active_scenario_fund_name'),
        ),
        migrations.AlterModelTable(
            name='scenariolist',
            table='scenarios',
        ),
        migrations.AddField(
            model_name='fundwaterfallenveloperules',
            name='envelope',
            field=models.ForeignKey(db_column='waterfall_envelope_id', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rest_api.fundwaterfallenvelopes'),
        ),
        migrations.AddField(
            model_name='fundwaterfallenveloperules',
            name='share_class',
            field=models.ForeignKey(db_column='share_class_id', on_delete=django.db.models.deletion.CASCADE, to='rest_api.shareclass'),
        ),
        migrations.AddField(
            model_name='fundwaterfallsteprules',
            name='fund_waterfall_step',
            field=models.ForeignKey(db_column='fund_waterfall_step_id', on_delete=django.db.models.deletion.CASCADE, related_name='step_rules', to='rest_api.fundwaterfallsteps'),
        ),
        migrations.AddField(
            model_name='fundwaterfallsteprules',
            name='share_class',
            field=models.ForeignKey(db_column='share_class_id', on_delete=django.db.models.deletion.CASCADE, to='rest_api.shareclass'),
        ),
        migrations.DeleteModel(
            name='FundWaterfallRules',
        ),
        migrations.AddConstraint(
            model_name='fundwaterfallenveloperules',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_percentage__gte', 0), ('fixed_percentage__lte', 100)), ('fixed_percentage__isnull', True), _connector='OR'), name='chk_fixed_percentage_range'),
        ),
        migrations.AlterUniqueTogether(
            name='fundwaterfallenveloperules',
            unique_together={('envelope', 'share_class')},
        ),
        migrations.AlterUniqueTogether(
            name='fundwaterfallsteprules',
            unique_together={('fund_waterfall_step', 'share_class')},
        ),
    ]
