# Generated by Django 5.2.10 on 2026-01-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_fundwaterfallenveloperules_fundwaterfallsteprules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareclass',
            name='document_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shareclass',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareclass',
            name='document_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareclass',
            name='fund',
            field=models.ForeignKey(db_column='fund_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='share_class', to='rest_api.fund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='distribution_method',
            field=models.CharField(choices=[('REDEMPTION_OF_SHARES', 'Redemption of shares'), ('DIVIDEND', 'Dividend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='issuance_method',
            field=models.CharField(choices=[('PRO_RATA_CALLED', 'Pro Rata Called Amount'), ('UPFRONT', 'Upfront')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='shareclass',
            constraint=models.UniqueConstraint(fields=('fund', 'share_class_name'), name='uq_share_class_fund_name'),
        ),
    ]
