# Generated by Django 5.2.10 on 2026-03-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_capitalaccountadjustednav_capitalaccountkpicache_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'managed': False, 'ordering': ['formation_date', 'legal_name', 'short_name']},
        ),
        migrations.AlterModelOptions(
            name='fundmanfeerules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fundwaterfallenveloperules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fundwaterfallenvelopes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fundwaterfallsteprules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fundwaterfallsteps',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scenarioduediligencefee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scenariolist',
            options={'managed': False, 'ordering': ['scenario_name', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='scenariosynthesis',
            options={'managed': False, 'ordering': ['synthesis_name', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='shareclass',
            options={'managed': False, 'ordering': ['share_class_name']},
        ),
        migrations.AlterModelOptions(
            name='waterfallstep',
            options={'managed': False, 'ordering': ['step_number']},
        ),
    ]
