from django.urls import path

from ..views.dealflow_views import (
    CalendarEventDetailView,
    CalendarEventLinkDealView,
    CalendarEventsView,
    CalendarMicrosoftConnectView,
    CalendarMicrosoftStatusView,
    CalendarMicrosoftSyncView,
    CalendarOptionsView,
    DealflowBoardMemberDetailView,
    DealflowBoardMembersView,
    DealflowBoardSnapshotDetailView,
    DealflowBoardView,
    DealflowCapTableEntriesView,
    DealflowCapTableColumnDetailView,
    DealflowCapTableColumnsView,
    DealflowCapTableDuplicateView,
    DealflowCapTableEntryDetailView,
    DealflowCapTableSnapshotDetailView,
    DealflowCapTableView,
    DealflowDealDocumentDetailView,
    DealflowDealDocumentsView,
    DealflowDealExternalContactDetailView,
    DealflowDealExternalContactsView,
    DealflowDealEventDetailView,
    DealflowDealEventsView,
    DealflowDealStageLogDetailView,
    DealflowDealStageLogView,
    DealflowDealDetailView,
    DealflowDealListCreateView,
    DealflowDashboardView,
    DealflowFieldConfigView,
    DealflowFundListView,
    DealflowKpiEntriesView,
    DealflowKpiEntryDetailView,
    DealflowKpiPeriodDetailView,
    DealflowKpisView,
    DealflowSetupItemDetailView,
    DealflowSetupItemsView,
    DealflowTaxonomyListView,
    DealflowUserListView,
    DealflowUserDetailView,
)


urlpatterns = [
    path("calendar/events/", CalendarEventsView.as_view(), name="calendar-events"),
    path("calendar/events/<uuid:event_id>/", CalendarEventDetailView.as_view(), name="calendar-event-detail"),
    path("calendar/events/<uuid:event_id>/link-deal/", CalendarEventLinkDealView.as_view(), name="calendar-event-link-deal"),
    path("calendar/options/", CalendarOptionsView.as_view(), name="calendar-options"),
    path("calendar/microsoft/status/", CalendarMicrosoftStatusView.as_view(), name="calendar-microsoft-status"),
    path("calendar/microsoft/connect/", CalendarMicrosoftConnectView.as_view(), name="calendar-microsoft-connect"),
    path("calendar/microsoft/sync/", CalendarMicrosoftSyncView.as_view(), name="calendar-microsoft-sync"),
    path("dealflow/dashboard/", DealflowDashboardView.as_view(), name="dealflow-dashboard"),
    path("dealflow/deals/", DealflowDealListCreateView.as_view(), name="dealflow-deals-list-create"),
    path("dealflow/deals/<uuid:deal_id>/", DealflowDealDetailView.as_view(), name="dealflow-deals-detail"),
    path("dealflow/deals/<uuid:deal_id>/events/", DealflowDealEventsView.as_view(), name="dealflow-deal-events"),
    path("dealflow/deals/<uuid:deal_id>/events/<uuid:event_id>/", DealflowDealEventDetailView.as_view(), name="dealflow-deal-event-detail"),
    path("dealflow/deals/<uuid:deal_id>/stage-logs/", DealflowDealStageLogView.as_view(), name="dealflow-stage-logs"),
    path("dealflow/deals/<uuid:deal_id>/stage-logs/<uuid:event_id>/", DealflowDealStageLogDetailView.as_view(), name="dealflow-stage-logs-detail"),
    path("dealflow/deals/<uuid:deal_id>/stage-log/", DealflowDealStageLogView.as_view(), name="dealflow-stage-log"),
    path("dealflow/deals/<uuid:deal_id>/stage-log/<uuid:event_id>/", DealflowDealStageLogDetailView.as_view(), name="dealflow-stage-log-detail"),
    path("dealflow/deals/<uuid:deal_id>/documents/", DealflowDealDocumentsView.as_view(), name="dealflow-deal-documents"),
    path("dealflow/deals/<uuid:deal_id>/documents/<uuid:document_id>/", DealflowDealDocumentDetailView.as_view(), name="dealflow-deal-document-detail"),
    path("dealflow/deals/<uuid:deal_id>/external-contacts/", DealflowDealExternalContactsView.as_view(), name="dealflow-deal-external-contacts"),
    path("dealflow/deals/<uuid:deal_id>/external-contacts/<uuid:contact_id>/", DealflowDealExternalContactDetailView.as_view(), name="dealflow-deal-external-contact-detail"),
    path("dealflow/deals/<uuid:deal_id>/kpis/", DealflowKpisView.as_view(), name="dealflow-kpis"),
    path("dealflow/deals/<uuid:deal_id>/kpi-periods/", DealflowKpisView.as_view(), name="dealflow-kpi-periods"),
    path("dealflow/deals/<uuid:deal_id>/kpis/<uuid:period_id>/", DealflowKpiPeriodDetailView.as_view(), name="dealflow-kpi-period-detail"),
    path("dealflow/deals/<uuid:deal_id>/kpi-periods/<uuid:period_id>/", DealflowKpiPeriodDetailView.as_view(), name="dealflow-kpi-periods-detail"),
    path("dealflow/deals/<uuid:deal_id>/kpis/<uuid:period_id>/entries/", DealflowKpiEntriesView.as_view(), name="dealflow-kpi-entries"),
    path("dealflow/deals/<uuid:deal_id>/kpi-periods/<uuid:period_id>/entries/", DealflowKpiEntriesView.as_view(), name="dealflow-kpi-periods-entries"),
    path("dealflow/deals/<uuid:deal_id>/kpis/entries/<uuid:entry_id>/", DealflowKpiEntryDetailView.as_view(), name="dealflow-kpi-entry-detail"),
    path("dealflow/deals/<uuid:deal_id>/kpi-periods/<uuid:period_id>/entries/<uuid:entry_id>/", DealflowKpiEntryDetailView.as_view(), name="dealflow-kpi-periods-entry-detail"),
    path("dealflow/deals/<uuid:deal_id>/board/", DealflowBoardView.as_view(), name="dealflow-board"),
    path("dealflow/deals/<uuid:deal_id>/board/<uuid:snapshot_id>/", DealflowBoardSnapshotDetailView.as_view(), name="dealflow-board-snapshot-detail"),
    path("dealflow/deals/<uuid:deal_id>/board/<uuid:snapshot_id>/members/", DealflowBoardMembersView.as_view(), name="dealflow-board-members"),
    path("dealflow/deals/<uuid:deal_id>/board/members/<uuid:member_id>/", DealflowBoardMemberDetailView.as_view(), name="dealflow-board-member-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/", DealflowCapTableView.as_view(), name="dealflow-cap-table"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/", DealflowCapTableView.as_view(), name="dealflow-cap-tables"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/<uuid:snapshot_id>/", DealflowCapTableSnapshotDetailView.as_view(), name="dealflow-cap-table-snapshot-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/<uuid:snapshot_id>/", DealflowCapTableSnapshotDetailView.as_view(), name="dealflow-cap-tables-snapshot-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/<uuid:snapshot_id>/entries/", DealflowCapTableEntriesView.as_view(), name="dealflow-cap-table-entries"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/<uuid:snapshot_id>/entries/", DealflowCapTableEntriesView.as_view(), name="dealflow-cap-tables-entries"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/entries/<uuid:entry_id>/", DealflowCapTableEntryDetailView.as_view(), name="dealflow-cap-table-entry-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/<uuid:snapshot_id>/entries/<uuid:entry_id>/", DealflowCapTableEntryDetailView.as_view(), name="dealflow-cap-tables-entry-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/<uuid:snapshot_id>/columns/", DealflowCapTableColumnsView.as_view(), name="dealflow-cap-tables-columns"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/<uuid:snapshot_id>/columns/<uuid:column_id>/", DealflowCapTableColumnDetailView.as_view(), name="dealflow-cap-tables-column-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-tables/<uuid:snapshot_id>/duplicate/", DealflowCapTableDuplicateView.as_view(), name="dealflow-cap-tables-duplicate"),
    path("dealflow/setup/<str:taxonomy_type>/", DealflowSetupItemsView.as_view(), name="dealflow-setup-items"),
    path("dealflow/setup/<str:taxonomy_type>/<uuid:item_id>/", DealflowSetupItemDetailView.as_view(), name="dealflow-setup-item-detail"),
    path("dealflow/field-config/", DealflowFieldConfigView.as_view(), name="dealflow-field-config"),
    path("dealflow/funds/", DealflowFundListView.as_view(), name="dealflow-funds-list"),
    path("dealflow/users/", DealflowUserListView.as_view(), name="dealflow-users-list"),
    path("dealflow/users/<uuid:user_id>/", DealflowUserDetailView.as_view(), name="dealflow-users-detail"),
    path("dealflow/taxonomy/", DealflowTaxonomyListView.as_view(), name="dealflow-taxonomy-list"),
]
