from django.urls import path

from ..views.dealflow_views import (
    DealflowBoardMemberDetailView,
    DealflowBoardMembersView,
    DealflowBoardSnapshotDetailView,
    DealflowBoardView,
    DealflowCapTableEntriesView,
    DealflowCapTableEntryDetailView,
    DealflowCapTableSnapshotDetailView,
    DealflowCapTableView,
    DealflowDealDocumentDetailView,
    DealflowDealDocumentsView,
    DealflowDealEventDetailView,
    DealflowDealEventsView,
    DealflowDealStageLogDetailView,
    DealflowDealStageLogView,
    DealflowDealDetailView,
    DealflowDealListCreateView,
    DealflowDashboardView,
    DealflowFundListView,
    DealflowKpiEntriesView,
    DealflowKpiEntryDetailView,
    DealflowKpiPeriodDetailView,
    DealflowKpisView,
    DealflowSetupItemDetailView,
    DealflowSetupItemsView,
    DealflowTaxonomyListView,
    DealflowUserListView,
)


urlpatterns = [
    path("dealflow/dashboard/", DealflowDashboardView.as_view(), name="dealflow-dashboard"),
    path("dealflow/deals/", DealflowDealListCreateView.as_view(), name="dealflow-deals-list-create"),
    path("dealflow/deals/<uuid:deal_id>/", DealflowDealDetailView.as_view(), name="dealflow-deals-detail"),
    path("dealflow/deals/<uuid:deal_id>/events/", DealflowDealEventsView.as_view(), name="dealflow-deal-events"),
    path("dealflow/deals/<uuid:deal_id>/events/<uuid:event_id>/", DealflowDealEventDetailView.as_view(), name="dealflow-deal-event-detail"),
    path("dealflow/deals/<uuid:deal_id>/stage-log/", DealflowDealStageLogView.as_view(), name="dealflow-stage-log"),
    path("dealflow/deals/<uuid:deal_id>/stage-log/<uuid:event_id>/", DealflowDealStageLogDetailView.as_view(), name="dealflow-stage-log-detail"),
    path("dealflow/deals/<uuid:deal_id>/documents/", DealflowDealDocumentsView.as_view(), name="dealflow-deal-documents"),
    path("dealflow/deals/<uuid:deal_id>/documents/<uuid:document_id>/", DealflowDealDocumentDetailView.as_view(), name="dealflow-deal-document-detail"),
    path("dealflow/deals/<uuid:deal_id>/kpis/", DealflowKpisView.as_view(), name="dealflow-kpis"),
    path("dealflow/deals/<uuid:deal_id>/kpis/<uuid:period_id>/", DealflowKpiPeriodDetailView.as_view(), name="dealflow-kpi-period-detail"),
    path("dealflow/deals/<uuid:deal_id>/kpis/<uuid:period_id>/entries/", DealflowKpiEntriesView.as_view(), name="dealflow-kpi-entries"),
    path("dealflow/deals/<uuid:deal_id>/kpis/entries/<uuid:entry_id>/", DealflowKpiEntryDetailView.as_view(), name="dealflow-kpi-entry-detail"),
    path("dealflow/deals/<uuid:deal_id>/board/", DealflowBoardView.as_view(), name="dealflow-board"),
    path("dealflow/deals/<uuid:deal_id>/board/<uuid:snapshot_id>/", DealflowBoardSnapshotDetailView.as_view(), name="dealflow-board-snapshot-detail"),
    path("dealflow/deals/<uuid:deal_id>/board/<uuid:snapshot_id>/members/", DealflowBoardMembersView.as_view(), name="dealflow-board-members"),
    path("dealflow/deals/<uuid:deal_id>/board/members/<uuid:member_id>/", DealflowBoardMemberDetailView.as_view(), name="dealflow-board-member-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/", DealflowCapTableView.as_view(), name="dealflow-cap-table"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/<uuid:snapshot_id>/", DealflowCapTableSnapshotDetailView.as_view(), name="dealflow-cap-table-snapshot-detail"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/<uuid:snapshot_id>/entries/", DealflowCapTableEntriesView.as_view(), name="dealflow-cap-table-entries"),
    path("dealflow/deals/<uuid:deal_id>/cap-table/entries/<uuid:entry_id>/", DealflowCapTableEntryDetailView.as_view(), name="dealflow-cap-table-entry-detail"),
    path("dealflow/setup/<str:taxonomy_type>/", DealflowSetupItemsView.as_view(), name="dealflow-setup-items"),
    path("dealflow/setup/<str:taxonomy_type>/<uuid:item_id>/", DealflowSetupItemDetailView.as_view(), name="dealflow-setup-item-detail"),
    path("dealflow/funds/", DealflowFundListView.as_view(), name="dealflow-funds-list"),
    path("dealflow/users/", DealflowUserListView.as_view(), name="dealflow-users-list"),
    path("dealflow/taxonomy/", DealflowTaxonomyListView.as_view(), name="dealflow-taxonomy-list"),
]
